src/Entity/Book.php
<?php

namespace App\Entity;

use App\Repository\BookRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BookRepository::class)]
class Book
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(type: Types::BIGINT, nullable: false)]
    private ?string $category_id = null;

    #[ORM\Column]
    private ?int $pages = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $publication_date = null;

    #[ORM\Column]
    private ?\DateTime $created_at = null;

    #[ORM\Column]
    private ?\DateTime $updated_at = null;

    #[ORM\ManyToOne(targetEntity: Category::class, inversedBy: 'books')]
    #[ORM\JoinColumn(name: 'category_id', referencedColumnName: 'id', nullable: false)]
    private ?Category $category = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getCategoryId(): ?string
    {
        return $this->category_id;
    }

    public function setCategoryId(string $category_id): static
    {
        $this->category_id = $category_id;

        return $this;
    }

    public function getPages(): ?int
    {
        return $this->pages;
    }

    public function setPages(int $pages): static
    {
        $this->pages = $pages;

        return $this;
    }

    public function getPublicationDate(): ?\DateTimeInterface
    {
        return $this->publication_date;
    }

    public function setPublicationDate(\DateTimeInterface $publication_date): static
    {
        $this->publication_date = $publication_date;

        return $this;
    }

    public function getCreatedAt(): ?\DateTime
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTime $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTime
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTime $updated_at): static
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): static
    {
        $this->category = $category;

        return $this;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;


use App\Repository\BookReadRepository;
use App\Repository\BookRepository;
use App\Repository\CategoryRepository;
use Doctrine\DBAL\Exception;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Bundle\SecurityBundle\Security;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

class HomeController extends AbstractController
{

    public function __construct(BookReadRepository $bookReadRepository, private readonly Security $security, BookRepository $bookRepository, CategoryRepository $categoryRepository, entityManagerInterface $em)
    {
        $this->bookReadRepository = $bookReadRepository;
        $this->bookRepository = $bookRepository;
        $this->categoryRepository = $categoryRepository;
        $this->em = $em;
    }

    /**
     * Affiche la page d'accueil avec les livres lus et non lus par l'utilisateur, ainsi que les évaluations moyennes par catégorie.
     *
     * Cette méthode vérifie si un utilisateur est connecté, récupère les livres lus et non lus,
     * et les catégories associées aux livres. Elle passe ces informations à la vue pour l'affichage.
     *
     * @throws Exception Si une erreur liée à la base de données se produit.
     *
     * @return Response La réponse contenant la vue rendue de la page d'accueil.
     */
    #[Route('/', name: 'app.home')]
    public function index(): Response
    {
        $user = $this->security->getUser();

        if (!$user) {
            return $this->redirectToRoute('auth.login');
        }

        $booksNotRead  = $this->bookReadRepository->findByUserId($user->getId(), false);
        $booksRead  = $this->bookReadRepository->findByUserId($user->getId(), true);

        $book = $this->bookRepository->findAll();

        $data = $this->bookReadRepository->findAverageRatingsByCategory($user->getId());

        return $this->render('pages/home.html.twig', [
            'booksNotRead' => $booksNotRead,
            'name' => 'Accueil',
            'user' => $user,
            'books' => $book,
            'booksRead' => $booksRead,
            'data' => json_encode($data),
        ]);
    }
}

templates/components/home/booksRead.html.twig
<div class="card card-grid h-full min-w-full">
    <div class="card-header">
        <h3 class="card-title">
            Mes lectures terminées
        </h3>
        <div class="input input-sm max-w-48">
            <i class="ki-filled ki-magnifier"></i>
            <input data-datatable-search="#read-books-table" placeholder="Rechercher" type="text"/>
        </div>
    </div>
    <div class="card-body">
        <div id="read-books-table" data-datatable="true" data-datatable-page-size="5">
            <div class="scrollable-x-auto">
                <table class="table table-border" data-datatable-table="true">
                    <thead>
                    <tr>
                        <th class="min-w-[280px]">
                                <span class="sort asc">
                                    <span class="sort-label">Livre</span>
                                    <span class="sort-icon"></span>
                                </span>
                        </th>
                        <th class="min-w-[135px]">
                                <span class="sort asc">
                                    <span class="sort-label">Catégorie</span>
                                    <span class="sort-icon"></span>
                                </span>
                        </th>
                        <th class="min-w-[135px]">
                                <span class="sort asc">
                                    <span class="sort-label">Note</span>
                                    <span class="sort-icon"></span>
                                </span>
                        </th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for bookRead in booksRead %}
                        <tr>
                            <td>
                                <div class="flex flex-col gap-2">
                                    <span class="text-2sm text-gray-700 font-normal leading-3">
                                        {{ bookRead.book.name }}
                                    </span>
                                </div>
                            </td>
                            <td>{{ bookRead.book.category.name }}</td>
                            <td>
                                <div class="rating">
                                    {% for i in 1..5 %}
                                        <div class="rating-label {% if bookRead.rating >= i %}checked{% endif %}">
                                            <i class="rating-on ki-solid ki-star text-base leading-none"></i>
                                        </div>
                                    {% endfor %}
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="card-footer justify-center md:justify-between flex-col md:flex-row gap-5 text-gray-600 text-2sm font-medium">
                <div class="flex items-center gap-2 order-2 md:order-1">
                    Show
                    <select class="select select-sm w-16" data-datatable-size="true" name="perpage"></select>
                    per page
                </div>
                <div class="flex items-center gap-4 order-1 md:order-2">
                    <span data-datatable-info="true"></span>
                    <div class="pagination hidden" data-datatable-pagination="true">
                        <!-- Pagination here -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

templates/components/home/booksReading.html.twig
<!-- book_list.html.twig -->
<div class="card card-grid h-full min-w-full">
    <div class="card-header">
        <h3 class="card-title">Mes lectures en cours</h3>
        <div class="input input-sm max-w-48">
            <i class="ki-filled ki-magnifier"></i>
            <input data-datatable-search="#current-books-table" placeholder="Rechercher" type="text"/>
        </div>
    </div>
    <div class="card-body">
        <div id="current-books-table" data-datatable="true" data-datatable-page-size="5">
            <div class="scrollable-x-auto">
                <table class="table table-border" data-datatable-table="true">
                    <thead>
                    <tr>
                        <th class="min-w-[280px]">
                                <span class="sort asc">
                                    <span class="sort-label">Livre</span>
                                    <span class="sort-icon"></span>
                                </span>
                        </th>
                        <th class="max-w-[135px] text-end">
                                <span class="sort">
                                    <span class="sort-label">Modifié le</span>
                                    <span class="sort-icon"></span>
                                </span>
                        </th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for bookRead in booksNotRead %}
                        <tr>
                            <td>
                                <div class="flex flex-col gap-2">
                                    <a
                                            class="edit-book leading-none font-medium text-sm text-gray-900 hover:text-primary"
                                            href="#"
                                            data-modal-toggle="#book_reading_modal"
                                            data-readbook="{{ bookRead.id }}"
                                            data-book="{{ bookRead.book.id }}"
                                            data-description="{{ bookRead.description }}"
                                            data-rating="{{ bookRead.rating|number_format(1, '.', '') }}"
                                            data-checked="{{ bookRead.isRead ? 'checked' : '' }}"
                                            title="Modifier la lecture"
                                    >
                                        {{ bookRead.book.name }}
                                    </a>
                                    <span class="text-2sm text-gray-700 font-normal leading-3">
                                        {{ bookRead.book.description }}
                                    </span>
                                </div>
                            </td>
                            <td class="text-end">
                                {{ bookRead.updatedAt|date('d/m/Y à H:i') }}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

templates/components/home/radarChart.html.twig
<div class="card h-full">
    <div class="card-header">
        <h3 class="card-title">
            Ma préférence sur les catégories lu.
        </h3>
    </div>
    <div class="card-body flex flex-col gap-5">
        <figure>
            <div id="chart"></div>
        </figure>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>
<script>
    var data = {{ data|raw }};
    const rating = data.map(item => item[1]); // Récupère les ratings
    const categories = data.map(item => item[0]); // Récupère les catégories

    console.log(categories);
    console.log(rating);

    var options = {
        series: [{
            name: "Ratings",
            data: rating  // Les notes moyennes pour chaque catégorie
        }],
        chart: {
            type: 'radar',
            height: 350
        },
        xaxis: {
            categories: categories
        },
        plotOptions: {
            radar: {
                size: 100,
                polygons: {
                    strokeColor: '#e8e8e8',
                    fill: {
                        colors: ['#f8f8f8', '#fff']
                    }
                }
            }
        }
    };

    var chart = new ApexCharts(document.querySelector("#chart"), options);
    chart.render();
</script>